//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TiendaMVC.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Almacen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacen()
        {
            this.AlmacenProducto = new HashSet<AlmacenProducto>();
        }
        [DisplayName("ID")]
        public int id { get; set; }

        [Required]
        [DisplayName("Ciudad")]
        public string ciudad { get; set; }

        [Required]
        [RegularExpression(@"\d{5}", ErrorMessage = "El código postal debe tener 5 dígitos")]
        [DisplayName("Código postal")]
        public string cp { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmacenProducto> AlmacenProducto { get; set; }
    }
}
