//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TiendaMVC.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.AlmacenProducto = new HashSet<AlmacenProducto>();
            this.Etiqueta = new HashSet<Etiqueta>();
        }

        public int id { get; set; }

        [Required]
        [DisplayName("Nombre del producto")]
        public string nombre { get; set; }

        [DisplayName("Descripción")]
        [DataType(DataType.MultilineText)]
        public string descripcion { get; set; }

        [DisplayName("Precio de venta")]
        [DataType(DataType.Currency)]
        public decimal precioVenta { get; set; }

        [DisplayName("Precio de coste")]
        [DataType(DataType.Currency)]
        public decimal precioCoste { get; set; }

        public string fabricante { get; set; }

        public int categoria { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlmacenProducto> AlmacenProducto { get; set; }
        public virtual Categoria Categoria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etiqueta> Etiqueta { get; set; }
    }
}
